[package]
name = "glrx"
version = "0.1.0"
description = "GNSS software-defined receiver"
documentation = "https://docs.rs/glrx"
homepage = "https://github.com/MiCkEyZzZ/glrx"
repository = "https://github.com/MiCkEyZzZ/glrx"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"

[[bin]]
name = "glrx"
path = "src/main.rs"

[features]
# Default feature set is empty.
# The crate compiles in no_std environments with no flags enabled.
default = []
sdr = []

[dependencies]
byteorder = "1.5.0"
log = "0.4.29"
num-complex = "0.4.6"
parking_lot = "0.12.5"
rustfft = "6.4.1"

[dev-dependencies]
tempfile = "3.27.0"
criterion = "0.8.2"
flamegraph = "0.6.11"
tokio-console = "0.1.14"
