[package]
name = "benches"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
glrx = { path = ".." }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
num-complex = "0.4.6"

[[bench]]
name = "dsp_benchmark"
path = "benches/dsp_benchmark.rs"
harness = false
