name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      # быстрые бинарники вместо cargo install
      - uses: taiki-e/install-action@v2
        with:
          tool: just,taplo-cli,cargo-deny

      # формат
      - run: just fmt --check

      # clippy (строго, но быстро)
      - run: just clippy

      # тесты
      - run: just test
