name: Security

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo install cargo-audit --locked
      - run: cargo install cargo-deny --locked
      - run: cargo install cargo-machete --locked

      - run: cargo audit
      - run: cargo deny check
      - run: cargo machete
